steps:
  - imports:
      align: group
  - language_pragmas:
      style: vertical
      remove_redundant: true
  - records: {}
  - trailing_whitespace: {}
columns: 80
language_extensions:
  - MultiParamTypeClasses
  - FlexibleContexts
