language: haskell-stack

env:
  - GHCVER=7.10.3 STACK_YAML=stack-lts-6.yaml PEDANTIC=YES
  - GHCVER=8.0.1 STACK_YAML=stack-ghc-8.0.yaml PEDANTIC=YES

matrix:
  fast_finish: true

branches:
  only:
    - master
