name: futurice-prelude
version: 0.1.9.0
synopsis: Futurice Prelude
description: |
  'Futurice.Prelude' is used in Futurice apps:
  .
  @
  import Prelude ()
  import Futurice.Prelude
  @
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-futurice-prelude
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3
extra-source-files:
- README.md

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.10
    - aeson
    - ansi-pretty
    - ansi-wl-pprint
    - base-compat           ==0.9.1
    - base-orphans          ==0.5.4
    - binary
    - binary-orphans
    - bytestring
    - cassava
    - composition-extra     >=2.0.0
    - constraints
    - intervals
    - containers
    - deepseq
    - deepseq-generics      >=0.1.1.2  && <0.3
    - exceptions
    - generics-sop          >=0.2.1.0  && <0.3
    - generics-sop-lens     >=0.1.1.0  && <0.2
    - ghc-prim
    - hashable
    - hashable-time
    - lens
    - monad-logger
    - monad-time
    - monadcryptorandom     >=0.7.0   && <=0.7.1
    - mtl
    - nats
    - operational
    - QuickCheck
    - quickcheck-instances
    - random-shuffle
    - semigroups
    - swagger2              >= 2.0.2
    - tagged
    - text
    - time
    - transformers
    - unordered-containers
    - vector
    - vector-instances

tests:
  futurice-prelude-tests:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - base
      - cassava
      - aeson
      - generics-sop
      - futurice-prelude
      - QuickCheck
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - vector
