name: futurice-prelude
version: 0.1.10.0
synopsis: Futurice Prelude
description: |
  'Futurice.Prelude' is used in Futurice apps:
  .
  @
  import Prelude ()
  import Futurice.Prelude
  @
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-futurice-prelude
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3
extra-source-files:
- README.md

ghc-options: -Wall

default-extensions:
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - ScopedTypeVariables

library:
  source-dirs: src
  dependencies:
    - base                  >=4.8      && <4.10
    - aeson                 >=1.0      && <1.1
    - aeson-compat          >=0.3.6    && <0.4
    - ansi-pretty
    - ansi-wl-pprint        >=0.6.7.3  && <0.7
    - array                 >=0.5.1.0  && <0.6
    - async                 >=2.1.0    && <2.2
    - base-compat           ==0.9.1
    - base-orphans          ==0.5.4
    - bifunctors
    - binary
    - binary-orphans        ==0.1.5.1
    - binary-tagged         ==0.1.4.0  
    - bytestring
    - cassava               >=0.4.5.0  && <0.5
    - case-insensitive      >=1.2.0.7  && <1.3
    - composition-extra     >=2.0.0    && <2.1
    - constraints           >=0.8      && <0.9
    - containers
    - deepseq               >=1.4.1.1  && <1.5
    - exceptions            >=0.8.3    && <0.9
    - http-api-data         >=0.3.1    && <0.4
    - generics-sop          >=0.2.1.0  && <0.3
    - generics-sop-lens     >=0.1.1.0  && <0.2
    - ghc-prim
    - github                >=0.15     && <0.16
    - hashable              >=1.2.4
    - hashable-time         >=0.2      && <0.3
    - intervals             >=0.7.2    && <0.7.3
    - JuicyPixels           >=3.2.8    && <3.3
    - lens                  >=4.13     && <4.15
    - lucid                 >=2.9.6    && <2.9.7  # MonadReader instance
    - keys                  >=3.11     && <3.12
    - monad-logger          >=0.3.19   && <0.4
    - monad-time            >=0.2      && <0.3
    - monadcryptorandom     >=0.7.0    && <0.7.2
    - mtl                   >=2.2.1    && <2.3
    - nats
    - parsec                >=3.1.11   && <3.2
    - postgresql-simple     >=0.5.2.1  && <0.6
    - QuickCheck
    - quickcheck-instances  ==0.3.12
    - random-shuffle        ==0.0.4
    - semigroups
    - swagger2              >=2.1.3    && <2.2
    - tagged                >=0.8.4    && <0.9
    - text
    - these                 >=0.7.2    && <0.8
    - time                  >=1.5.0.1  && <1.7
    - time-parsers          >=0.1.1.0  && <0.2
    - transformers
    - tz                    >=0.1.2.0  && <0.2
    - reducers              >=3.12.1   && <3.13
    - transformers-compat   >=0.4.0.4  && <0.6 ## Bump to 0.5?
    - unordered-containers  >=0.2.7.1  && <0.3
    - uuid                  >=1.3.12   && <1.4
    - uuid-aeson            >=0.1.1.0  && <0.2
    - vector                >=0.11.0.0 && <0.12
    - vector-instances      ==3.3.1

    # Needed for swagger instances
    - insert-ordered-containers

tests:
  futurice-prelude-tests:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - base
      - cassava
      - aeson
      - generics-sop
      - futurice-prelude
      - QuickCheck
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - vector
